language: objective-c

branches:
 only:
 - master

xcode_project: Inetty.xcodeproj
xcode_scheme: UnitTests
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

before_install:
- brew update
- brew upgrade xctool
- brew install carthage
- carthage bootstrap --verbose

script:
- xcodebuild clean build test -project Inetty.xcodeproj -scheme UnitTests

